AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ProductsAPI

  ResourceProducts:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: 'products'

  MethodGetProducts:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ResourceProducts
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/lmb-list-products/invocations'
        IntegrationResponses:
          - StatusCode: 200

  MethodAddProduct:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ResourceProducts
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/lmb-add-product/invocations'
        IntegrationResponses:
          - StatusCode: 200
  
  MethodDeleteProduct:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ResourceProducts
      HttpMethod: DELETE
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/lmb-delete-product/invocations'
        IntegrationResponses:
          - StatusCode: 200

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - MethodGetProducts
      - MethodAddProduct
      - MethodDeleteProduct
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: dev

Outputs:
  ApiEndpoint:
    Description: 'API endpoint URL for Prod stage'
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev'
