openapi: "3.0.1"
info:
  title: "POS System API"
  version: "1.0.0"
paths:
  /products:
    get:
      summary: "List products"
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${region}:${accountId}:function:lmb-list-products/invocations
        httpMethod: POST
        type: "aws_proxy"
      responses:
        '200':
          description: "Successful response"

    post:
      summary: "Add a new product"
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${region}:${accountId}:function:lmb-add-product/invocations
        httpMethod: POST
        type: "aws_proxy"
      responses:
        '201':
          description: "Product added successfully"

    delete:
      summary: "Delete a product"
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${region}:${accountId}:function:lmb-delete-product/invocations
        httpMethod: POST
        type: "aws_proxy"
      responses:
        '200':
          description: "Product deleted successfully"
