name: Deploy API Gateway

on:
  push:
    branches:
      - main

jobs:
  deploy-api-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy API Gateway using CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file ./templates/api_gateway.yaml \
            --stack-name my-api-gateway-stack \
            --capabilities CAPABILITY_IAM

